import "./global.css";
import NavBar from "./components/Navbar/page";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header className="bg-gray-100 ">
         <div className="container mx-auto">
          <NavBar/>
         </div>
         
        </header>
      <main className="container mx-auto p-10"> {children}</main>
        <footer className="text-grey-400 text-center text-xs py-5">CopyRight &#64; {new Date().getFullYear()}-All right Reserved</footer>
      </body>
    </html>
  );
}
