import "./global.css";
import NavBar from "./components/Navbar/page";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header className="bg-gray-100 ">
         <div className="container mx-auto">
          <NavBar/>
         </div>
         
        </header>
        {children}
        <footer>Footer</footer>
      </body>
    </html>
  );
}
